@preconcurrency import AVFoundation
import Foundation
import Speech

/// Turns an imported audio/video file into a normal Meeting — transcript,
/// on-device summary, graph entities, exported note — with zero network.
///
/// Two pieces:
/// - `FileImportEngine` (actor): opens the file, decodes+resamples it **incrementally**
///   (never the whole file into memory), streams the chunks through the on-device
///   recognizer, and returns a finished, timed transcript. All of the CPU-heavy decode
///   loop runs off the main actor inside the actor's isolation.
/// - `FileImportCoordinator` (`@MainActor ObservableObject`): the UI-facing orchestrator.
///   Enforces model exclusivity (no import while a dictation or recording is live —
///   imports spin up 1–4 extra analyzers and must not compete), drives one import at a
///   time, publishes progress, and on success persists the Meeting + folds it into the
///   context graph exactly the way `MeetingRecorder.stop()` does.
///
/// This is the "drop an m4a on the Meetings tab and it becomes a meeting" feature; the
/// recognition path is reused read-only (a fresh `TranscriptionEngine`, or the
/// multilingual `MultiLangStreamTranscriber`), so there is no new model behavior to gate.

// MARK: - Errors

enum FileImportError: LocalizedError, Sendable {
    case unsupportedType(String)
    case cannotOpen(String)
    case noAudioTrack(String)
    case speechUnavailable
    case emptyTranscript
    case cancelled

    var errorDescription: String? {
        switch self {
        case .unsupportedType(let name):
            return "Talkie can’t import “\(name)” — it isn’t an audio or video file it recognizes."
        case .cannotOpen(let name):
            return "Talkie couldn’t open “\(name)”."
        case .noAudioTrack(let name):
            return "“\(name)” has no audio track to transcribe."
        case .speechUnavailable:
            return "On-device speech recognition isn’t available on this Mac."
        case .emptyTranscript:
            return "Talkie couldn’t make out any speech in that file."
        case .cancelled:
            return "Import cancelled."
        }
    }
}

// MARK: - Supported types

/// The file kinds `FileImportEngine` accepts. Audio opens with `AVAudioFile`; video
/// (which carries an audio track) is demuxed with `AVAssetReader`. Kept as a plain
/// extension allowlist so the drop target and the open panel agree on one source of
/// truth, and an unknown drop is rejected loudly rather than silently no-op'd.
enum ImportableMedia {
    /// Container extensions that hold PCM-decodable audio directly.
    static let audioExtensions: Set<String> = ["m4a", "mp3", "wav", "aiff", "aif", "flac", "caf", "aac"]
    /// Video containers whose audio track we demux + transcribe.
    static let videoExtensions: Set<String> = ["mp4", "mov", "m4v"]

    static var allExtensions: Set<String> { audioExtensions.union(videoExtensions) }

    static func isVideo(_ url: URL) -> Bool { videoExtensions.contains(url.pathExtension.lowercased()) }
    static func isAudio(_ url: URL) -> Bool { audioExtensions.contains(url.pathExtension.lowercased()) }
    static func isSupported(_ url: URL) -> Bool { allExtensions.contains(url.pathExtension.lowercased()) }

    /// Filter a dropped/opened batch to just the files we can transcribe. Pure so the
    /// drop target can be unit-tested without touching the filesystem.
    static func supported(in urls: [URL]) -> [URL] { urls.filter(isSupported) }
}

// MARK: - Result

/// The finished, `Sendable` product of one import — everything the coordinator needs
/// to construct a `Meeting` on the main actor. The transcript is already rendered and
/// trimmed; the summary is generated by the coordinator (it owns the model-exclusivity
/// window and the `MeetingSummarizer`), keeping the engine focused on decode+recognize.
struct FileImportResult: Sendable {
    /// Rendered transcript body (solo-speaker → plain text, per `MeetingTranscriptRenderer`).
    var transcript: String
    /// Audio length in seconds, measured from the source file (before resample).
    var durationSec: Double
}

// MARK: - Engine

/// Decodes + transcribes one file. An `actor` so the decode loop — genuinely CPU-heavy
/// — runs off the main actor, and the non-`Sendable` `AVAudioFile`/`AVAssetReader`
/// stay confined to its isolation (never crossing an isolation boundary).
actor FileImportEngine {
    /// ~1 second of audio per decode step at the analyzer's sample rate, so we feed the
    /// recognizer incrementally (like live audio) instead of buffering the whole file.
    /// A frame count is derived from the actual analyzer format at decode time.
    private static let chunkSeconds: Double = 1.0

    static var isAvailable: Bool { TranscriptionEngine.isAvailable }

    /// Import `url`, streaming progress (0…1, fraction of audio fed) to `onProgress`.
    /// `localeIDs` is the user's spoken languages; when ≥2 distinct and the multilingual
    /// transcriber is available, lanes are started and the per-language vote resolves the
    /// transcript. Otherwise a single fresh `TranscriptionEngine` pinned to `primaryLocale`
    /// does the work. Throws `FileImportError.cancelled` if the surrounding Task is
    /// cancelled between chunks — leaving nothing persisted.
    func importFile(
        url: URL,
        primaryLocale: String,
        localeIDs: [String],
        onProgress: @escaping @Sendable (Double) -> Void
    ) async throws -> FileImportResult {
        guard TranscriptionEngine.isAvailable else { throw FileImportError.speechUnavailable }
        guard ImportableMedia.isSupported(url) else {
            throw FileImportError.unsupportedType(url.lastPathComponent)
        }

        let distinct = LanguageDetector.distinctByCode(localeIDs)
        let useMulti = distinct.count > 1 && MultiLangStreamTranscriber.isAvailable

        // Try the multilingual lanes first when the user speaks several languages; if
        // the lanes can't start (models missing, analyzer cap), fall back to a single
        // fresh engine — never the shared mic engine.
        if useMulti {
            if let result = try await transcribeMultiLang(
                url: url, primaryLocale: primaryLocale, distinct: distinct, onProgress: onProgress
            ) {
                return result
            }
        }
        return try await transcribeSingle(url: url, primaryLocale: primaryLocale, onProgress: onProgress)
    }

    /// Single-locale path: a fresh `TranscriptionEngine` (never the shared mic engine),
    /// fed chunk-by-chunk as they're decoded, then finalized. The segment handler stamps
    /// each finalized segment into a `TurnLog` so the rendered transcript matches a
    /// recording's shape.
    private func transcribeSingle(
        url: URL,
        primaryLocale: String,
        onProgress: @escaping @Sendable (Double) -> Void
    ) async throws -> FileImportResult {
        let engine = TranscriptionEngine(localeIdentifier: primaryLocale)
        let log = TurnLog(startedAt: Date())
        let session: (format: AVAudioFormat, continuation: AsyncStream<AnalyzerInput>.Continuation)
        do {
            session = try await engine.beginSession(segmentHandler: { segment in log.add(.me, segment) })
        } catch {
            throw FileImportError.speechUnavailable
        }

        let duration: Double
        do {
            duration = try await decodeAndFeed(url: url, target: session.format, onProgress: onProgress) { buffer in
                session.continuation.yield(AnalyzerInput(buffer: buffer))
            }
        } catch {
            session.continuation.finish()
            _ = await engine.finishSessionDetailed()
            throw error
        }

        session.continuation.finish()
        _ = await engine.finishSessionDetailed()

        let transcript = MeetingTranscriptRenderer.render(log.snapshot())
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !transcript.isEmpty else { throw FileImportError.emptyTranscript }
        return FileImportResult(transcript: transcript, durationSec: duration)
    }

    /// Multilingual path: fan the decoded chunks into `MultiLangStreamTranscriber`'s
    /// continuation (identical to how `MeetingRecorder` feeds it), then resolve the
    /// per-language vote at the end. Returns nil if the lanes couldn't start (the caller
    /// then uses the single-locale path).
    private func transcribeMultiLang(
        url: URL,
        primaryLocale: String,
        distinct: [String],
        onProgress: @escaping @Sendable (Double) -> Void
    ) async throws -> FileImportResult? {
        let multi = MultiLangStreamTranscriber()
        guard let session = try? await multi.start(localeIDs: distinct) else {
            await multi.cancel()
            return nil
        }

        let duration: Double
        do {
            duration = try await decodeAndFeed(url: url, target: session.format, onProgress: onProgress) { buffer in
                session.continuation.yield(AnalyzerInput(buffer: buffer))
            }
        } catch {
            session.continuation.finish()
            _ = await multi.finish(anchorLocale: primaryLocale)
            throw error
        }

        session.continuation.finish()
        let spans = await multi.finish(anchorLocale: primaryLocale)

        // Rebuild a turn log from the language-routed spans, one timed turn per span, so
        // mid-file language switches survive into the rendered transcript.
        let log = TurnLog(startedAt: Date())
        log.replace(.me, withTimedTurns: spans.map { (elapsed: $0.start, text: $0.text) })
        let transcript = MeetingTranscriptRenderer.render(log.snapshot())
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !transcript.isEmpty else { throw FileImportError.emptyTranscript }
        return FileImportResult(transcript: transcript, durationSec: duration)
    }

    // MARK: Incremental decode

    /// Decode `url` to `target`'s format in ~1s chunks, handing each converted chunk to
    /// `feed`, and report progress as `framesFed / totalFrames`. Returns the source
    /// audio's duration in seconds. Dispatches to the audio-file or video-demux reader.
    /// Never materializes the whole file: exactly one chunk is resident at a time.
    private func decodeAndFeed(
        url: URL,
        target: AVAudioFormat,
        onProgress: @escaping @Sendable (Double) -> Void,
        feed: (AVAudioPCMBuffer) -> Void
    ) async throws -> Double {
        if ImportableMedia.isVideo(url) {
            return try await decodeVideo(url: url, target: target, onProgress: onProgress, feed: feed)
        }
        return try decodeAudioFile(url: url, target: target, onProgress: onProgress, feed: feed)
    }

    /// Incremental `AVAudioFile` reader: reads a fixed frame count per iteration,
    /// resamples that chunk to `target`, feeds it, and checks for cancellation between
    /// chunks. Progress is source-frames-read / total.
    private func decodeAudioFile(
        url: URL,
        target: AVAudioFormat,
        onProgress: @escaping @Sendable (Double) -> Void,
        feed: (AVAudioPCMBuffer) -> Void
    ) throws -> Double {
        guard let file = try? AVAudioFile(forReading: url) else {
            throw FileImportError.cannotOpen(url.lastPathComponent)
        }
        let sourceFormat = file.processingFormat
        let totalFrames = file.length
        let duration = sourceFormat.sampleRate > 0 ? Double(totalFrames) / sourceFormat.sampleRate : 0
        guard totalFrames > 0 else { throw FileImportError.emptyTranscript }

        // A chunk of source frames sized to ~chunkSeconds of the SOURCE audio (the read
        // happens in the source format; `conform` handles the resample afterwards).
        let chunkFrames = AVAudioFrameCount(max(1, Int(sourceFormat.sampleRate * Self.chunkSeconds)))
        var framesRead: AVAudioFramePosition = 0

        while framesRead < totalFrames {
            try Task.checkCancellation()
            guard let chunk = AVAudioPCMBuffer(pcmFormat: sourceFormat, frameCapacity: chunkFrames) else { break }
            do {
                try file.read(into: chunk, frameCount: chunkFrames)
            } catch {
                throw FileImportError.cannotOpen(url.lastPathComponent)
            }
            let got = chunk.frameLength
            guard got > 0 else { break }
            framesRead += AVAudioFramePosition(got)

            for converted in TranscriptionEngine.conform([chunk], to: target) where converted.frameLength > 0 {
                feed(converted)
            }
            let fraction = totalFrames > 0 ? min(1, Double(framesRead) / Double(totalFrames)) : 1
            onProgress(fraction)
        }
        onProgress(1)
        return duration
    }

    /// Incremental video-audio demux with `AVAssetReader`: pulls the audio track as
    /// LinearPCM float32 sample buffers one at a time (`copyNextSampleBuffer`), converts
    /// each to a PCM buffer, resamples to `target`, and feeds it. Fails loudly when the
    /// file has no audio track (a visible, friendly error — never a silent no-op).
    private func decodeVideo(
        url: URL,
        target: AVAudioFormat,
        onProgress: @escaping @Sendable (Double) -> Void,
        feed: (AVAudioPCMBuffer) -> Void
    ) async throws -> Double {
        let asset = AVURLAsset(url: url)
        // macOS 13+ prefers the async loaders over the deprecated sync `.tracks`/`.duration`.
        let tracks = (try? await asset.loadTracks(withMediaType: .audio)) ?? []
        guard let track = tracks.first else {
            throw FileImportError.noAudioTrack(url.lastPathComponent)
        }

        let reader: AVAssetReader
        do {
            reader = try AVAssetReader(asset: asset)
        } catch {
            throw FileImportError.cannotOpen(url.lastPathComponent)
        }

        // Ask the reader for deinterleaved float32 PCM so we can wrap each output sample
        // buffer as an AVAudioPCMBuffer and reuse the existing `conform` resampler.
        let outputSettings: [String: Any] = [
            AVFormatIDKey: kAudioFormatLinearPCM,
            AVLinearPCMBitDepthKey: 32,
            AVLinearPCMIsFloatKey: true,
            AVLinearPCMIsBigEndianKey: false,
            AVLinearPCMIsNonInterleaved: true,
        ]
        let output = AVAssetReaderTrackOutput(track: track, outputSettings: outputSettings)
        output.alwaysCopiesSampleData = false
        guard reader.canAdd(output) else { throw FileImportError.cannotOpen(url.lastPathComponent) }
        reader.add(output)
        guard reader.startReading() else { throw FileImportError.cannotOpen(url.lastPathComponent) }

        let totalDuration = (try? await asset.load(.duration).seconds) ?? 0
        let duration = totalDuration.isFinite ? max(0, totalDuration) : 0

        while reader.status == .reading {
            try Task.checkCancellation()
            guard let sample = output.copyNextSampleBuffer() else { break }
            guard let pcm = Self.pcmBuffer(from: sample) else { continue }
            for converted in TranscriptionEngine.conform([pcm], to: target) where converted.frameLength > 0 {
                feed(converted)
            }
            // Progress by presentation time / total duration — the reader has no frame
            // count up front, but sample timestamps map cleanly onto the known duration.
            if duration > 0 {
                let pts = CMSampleBufferGetPresentationTimeStamp(sample).seconds
                if pts.isFinite { onProgress(min(1, max(0, pts / duration))) }
            }
        }

        if reader.status == .failed {
            throw FileImportError.cannotOpen(url.lastPathComponent)
        }
        onProgress(1)
        return duration
    }

    /// Wrap one decoder-produced CMSampleBuffer (LinearPCM float32, non-interleaved) as
    /// an `AVAudioPCMBuffer`, copying its samples out so nothing aliases the CM block
    /// buffer after this returns. Returns nil for a sample with no usable audio.
    private static func pcmBuffer(from sample: CMSampleBuffer) -> AVAudioPCMBuffer? {
        guard let formatDesc = CMSampleBufferGetFormatDescription(sample),
              let asbdPtr = CMAudioFormatDescriptionGetStreamBasicDescription(formatDesc) else { return nil }
        var asbd = asbdPtr.pointee
        guard let format = AVAudioFormat(streamDescription: &asbd) else { return nil }

        let frames = CMSampleBufferGetNumSamples(sample)
        guard frames > 0,
              let buffer = AVAudioPCMBuffer(pcmFormat: format, frameCapacity: AVAudioFrameCount(frames)) else {
            return nil
        }
        buffer.frameLength = AVAudioFrameCount(frames)

        // Copy the decoded PCM into the AVAudioPCMBuffer's channel buffers via
        // CMSampleBufferCopyPCMDataIntoAudioBufferList (handles interleave/layout for us).
        let status = CMSampleBufferCopyPCMDataIntoAudioBufferList(
            sample,
            at: 0,
            frameCount: Int32(frames),
            into: buffer.mutableAudioBufferList
        )
        guard status == noErr else { return nil }
        return buffer
    }
}

// MARK: - Coordinator

/// Drives imports for the Meetings tab: one file at a time, off the main actor, with
/// live progress and hard model-exclusivity. `@MainActor` because it owns `@Published`
/// UI state and calls the main-actor `MeetingStore`/`ContextGraphStore`.
@MainActor
final class FileImportCoordinator: ObservableObject {
    /// One in-flight or queued import, surfaced to the progress row.
    struct Item: Identifiable, Sendable {
        let id = UUID()
        let url: URL
        var fileName: String { url.lastPathComponent }
    }

    /// The file currently being imported (nil when idle).
    @Published private(set) var active: Item?
    /// 0…1 progress of `active` (fraction of audio transcribed).
    @Published private(set) var progress: Double = 0
    /// Files waiting because a dictation/recording is live, or another import is running.
    @Published private(set) var queued: [Item] = []
    /// The most recent user-facing error (import failures are never silent).
    @Published private(set) var lastError: String?
    /// True while an import is deferred waiting for a live dictation/recording to end.
    @Published private(set) var waitingForSession = false

    private let engine = FileImportEngine()
    private let meetingStore: MeetingStore
    private let contextGraph: ContextGraphStore
    private let summarizer = MeetingSummarizer()

    /// The user's spoken-language config + live-session probes, injected from AppDelegate
    /// (mirrors how `MeetingRecorder` is wired). Imports must not run while any of these
    /// report a live session — an import spins up 1–4 extra analyzers.
    private let primaryLocale: () -> String
    private let spokenLanguages: () -> [String]
    private let isDictating: () -> Bool
    private let isProcessing: () -> Bool
    private let isRecording: () -> Bool

    private var runTask: Task<Void, Never>?

    init(
        meetingStore: MeetingStore,
        contextGraph: ContextGraphStore,
        primaryLocale: @escaping () -> String,
        spokenLanguages: @escaping () -> [String],
        isDictating: @escaping () -> Bool,
        isProcessing: @escaping () -> Bool,
        isRecording: @escaping () -> Bool
    ) {
        self.meetingStore = meetingStore
        self.contextGraph = contextGraph
        self.primaryLocale = primaryLocale
        self.spokenLanguages = spokenLanguages
        self.isDictating = isDictating
        self.isProcessing = isProcessing
        self.isRecording = isRecording
    }

    var isImporting: Bool { active != nil }

    /// True when a live dictation, its post-stop processing, or a meeting recording is in
    /// flight — imports defer rather than compete for the speech model / analyzers.
    private var sessionBusy: Bool { isDictating() || isProcessing() || isRecording() }

    /// Queue one or more files (unsupported files are dropped by the caller). Starts the
    /// pump if idle; otherwise they wait their turn.
    func enqueue(_ urls: [URL]) {
        let items = ImportableMedia.supported(in: urls).map { Item(url: $0) }
        guard !items.isEmpty else { return }
        lastError = nil
        queued.append(contentsOf: items)
        pump()
    }

    /// Cancel the active import (leaves no partial Meeting — nothing is persisted until
    /// the transcript is complete) and clear the queue.
    func cancel() {
        runTask?.cancel()
        runTask = nil
        queued.removeAll()
        active = nil
        progress = 0
        waitingForSession = false
    }

    /// Start the next queued import if nothing is running. If a session is live, mark
    /// "waiting" and retry shortly — imports never interleave with a live session.
    private func pump() {
        guard runTask == nil, active == nil, !queued.isEmpty else { return }

        if sessionBusy {
            waitingForSession = true
            // Re-check off a short delay rather than subscribing to three probes: the
            // wait is user-visible ("waiting for dictation to finish") and cheap.
            runTask = Task { [weak self] in
                try? await Task.sleep(for: .milliseconds(500))
                guard let self, !Task.isCancelled else { return }
                self.runTask = nil
                self.pump()
            }
            return
        }

        waitingForSession = false
        let item = queued.removeFirst()
        active = item
        progress = 0
        let primary = primaryLocale()
        let langs = spokenLanguages()

        runTask = Task { [weak self] in
            await self?.run(item: item, primaryLocale: primary, localeIDs: langs)
        }
    }

    /// Run one import end to end, then persist + ingest on the main actor and advance the
    /// queue. On failure surfaces a friendly error and moves on (never wedges the queue).
    private func run(item: Item, primaryLocale: String, localeIDs: [String]) async {
        defer {
            runTask = nil
            active = nil
            progress = 0
            pump()
        }

        let result: FileImportResult
        do {
            result = try await engine.importFile(
                url: item.url,
                primaryLocale: primaryLocale,
                localeIDs: localeIDs,
                onProgress: { [weak self] fraction in
                    Task { @MainActor in self?.updateProgress(item: item, fraction: fraction) }
                }
            )
        } catch is CancellationError {
            return // cancelled → nothing persisted
        } catch let error as FileImportError {
            if case .cancelled = error { return }
            lastError = error.errorDescription
            return
        } catch {
            lastError = error.localizedDescription
            return
        }

        if Task.isCancelled { return }

        // Summarize on-device (map-reduce is in-core now, so imports get full summaries).
        let summary = await summarizer.summarize(result.transcript) ?? ""
        if Task.isCancelled { return }

        // Build the Meeting via the existing MeetingStore construction API (Meeting.swift
        // is read-only this pass). Title from the filename (extension stripped);
        // startUnix from the file's content-creation date, falling back to now.
        let id = UUID()
        let start = Self.contentCreationDate(of: item.url) ?? Date()
        let meeting = Meeting(
            id: id,
            title: item.url.deletingPathExtension().lastPathComponent,
            startUnix: start.timeIntervalSince1970,
            durationSec: result.durationSec,
            transcript: result.transcript,
            summary: summary,
            participants: ["Imported"],
            source: "talkie (imported: \(item.url.lastPathComponent))",
            fileName: MeetingStore.fileName(for: start, id: id)
        )
        meetingStore.add(meeting)

        // Graph ingest exactly like MeetingRecorder.stop: candidates from the transcript,
        // tagged with meeting provenance, so imported meetings show up in recall/search.
        let provenance = Provenance(source: .meeting, sourceID: id.uuidString,
                                    dateUnix: start.timeIntervalSince1970, snippet: nil)
        contextGraph.ingest(ContextGraphExtractor.candidates(from: result.transcript), provenance: provenance)
    }

    private func updateProgress(item: Item, fraction: Double) {
        guard active?.id == item.id else { return }
        progress = min(1, max(0, fraction))
    }

    /// The file's content-creation date (when the audio was recorded, if the container
    /// carries it), falling back to nil so the caller uses "now". Read via URL resource
    /// values — no network, no extra frameworks.
    private static func contentCreationDate(of url: URL) -> Date? {
        let keys: Set<URLResourceKey> = [.contentModificationDateKey, .creationDateKey]
        guard let values = try? url.resourceValues(forKeys: keys) else { return nil }
        return values.creationDate ?? values.contentModificationDate
    }
}
